<Project>

  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsAotCompatible>false</IsAotCompatible>
    <ProjectsTargetFrameworks>net10.0</ProjectsTargetFrameworks>
    <NoWarn>$(NoWarn)</NoWarn>
  </PropertyGroup>


</Project>
