//using System.ComponentModel;
//using Agents.AI.Extensions.AITools;
//using Microsoft.Extensions.AI;
//using Microsoft.Extensions.Logging;

//namespace Agents.AI.Extensions.LiveVoice.IvrWorkflow.Tools;

///// <summary>
///// AI tools for the IVR orchestrator to control workflow execution and realtime agent personas.
///// These tools enable the orchestrator to manage the conversation flow, switch personas,
///// and handle escalations.
///// </summary>
//public class IvrOrchestratorTools : IAIToolCollection
//{
//    private readonly ILogger<IvrOrchestratorTools> _logger;
//    private readonly IvrWorkflowSession _ivrSession;

//    public IvrOrchestratorTools(
//        IvrWorkflowSession ivrSession,
//        ILogger<IvrOrchestratorTools> logger)
//    {
//        _ivrSession = ivrSession;
//        _logger = logger;
//    }
//    /// <summary>
//    /// Submits user input to the IVR workflow for processing.
//    /// </summary>
//    [Description("Submit the user's verbal input to the workflow engine. Returns the response you must speak to the user.")]
//    public async Task<string> SubmitIvrInputAsync(
//        [Description("The transcribed text of what the user just said.")] string userInput)
//    {
//        _logger.LogInformation("Submitting input to workflow session {SessionId}: {Input}", _ivrSession.SessionId, userInput);

//        // 1. Pass input to your existing IvrWorkflowSession
//        // This runs the guards, validators, and advances the step if valid.
//        var responsePrompt = await _ivrSession.ProcessMessageAsync(userInput);

//        // 2. If the workflow is complete, we might want to signal that, but usually
//        // simply returning the final message (e.g., "Card activated") is sufficient.
//        if (_ivrSession.IsComplete)
//        {
//            _logger.LogInformation("Workflow complete.");
//        }

//        // 3. Return the prompt generated by the C# Workflow (e.g. "Please enter your PIN")
//        // The Realtime Agent will treat this string as the result of the tool 
//        // and uses it to generate its voice response.
//        return responsePrompt ?? "I didn't understand. Please try again.";
//    }

//    /// <summary>
//    /// Gets the current state for context (optional, useful if Agent needs to know 'where' it is).
//    /// </summary>
//    [Description("Get the current status of the workflow.")]
//    public Task<IvrStateResult> GetIvrWorkflowStateAsync()
//    {
//        return Task.FromResult(new IvrStateResult
//        {
//            SessionId = _ivrSession.SessionId,
//            CurrentStep = _ivrSession.State.CurrentStepName ?? "Unknown",
//            Status = _ivrSession.State.Status.ToString(),
//            CompletedSteps = _ivrSession.State.CompletedSteps.ToList()
//        });
//    }

//    /// <summary>
//    /// Requests a change in the realtime agent persona for different interaction styles.
//    /// </summary>
//    /// <remarks>
//    /// NOTE: This is a placeholder implementation. In a full implementation, this would
//    /// trigger persona switching logic in the session activator.
//    /// </remarks>
//    [Description("Change the realtime voice agent persona. Use this to switch to different agent styles (e.g., 'escalation' for complex issues, 'sales' for purchases).")]
//    public Task<PersonaChangeResult> ChangeRealtimePersonaAsync(
//        [Description("The target persona name (e.g., 'escalation', 'sales', 'support', 'default')")] string personaName,
//        [Description("Reason for the persona change")] string? reason = null)
//    {
//        _logger.LogInformation("Persona change requested: {PersonaName}, Reason: {Reason}", personaName, reason);

//        // NOTE: Placeholder - actual implementation will trigger orchestrator event
//        return Task.FromResult(new PersonaChangeResult
//        {
//            Success = true,
//            PersonaName = personaName,
//            Message = $"Switching to {personaName} persona"
//        });
//    }

//    /// <summary>
//    /// Initiates handoff to a human operator when the AI cannot handle the request.
//    /// </summary>
//    /// <remarks>
//    /// NOTE: This is a placeholder implementation. In a full implementation, this would
//    /// trigger handoff logic in the session activator.
//    /// </remarks>
//    [Description("Hand off the conversation to a human operator. Use this when the issue is complex, the user is frustrated, or AI assistance is insufficient.")]
//    public Task<HandoffResult> HandoffToHumanAsync(
//        [Description("Reason for the handoff (e.g., 'Complex technical issue', 'Customer escalation')")] string reason,
//        [Description("Priority level: 'low', 'normal', 'high', 'urgent'")] string priority = "normal",
//        [Description("Summary of the conversation so far")] string? conversationSummary = null)
//    {
//        _logger.LogInformation("Handoff requested: Priority={Priority}, Reason={Reason}", priority, reason);

//        // NOTE: Placeholder - actual implementation will trigger orchestrator event
//        return Task.FromResult(new HandoffResult
//        {
//            Success = true,
//            HandoffId = Guid.NewGuid().ToString(),
//            EstimatedWaitTime = "2-3 minutes",
//            Message = $"Connecting you to an operator. Reason: {reason}"
//        });
//    }


//    /// <inheritdoc/>
//    public IEnumerable<AITool> AsAITools()
//    {
//        yield return AIFunctionFactory.Create(SubmitIvrInputAsync);
//        yield return AIFunctionFactory.Create(ChangeRealtimePersonaAsync);
//        yield return AIFunctionFactory.Create(HandoffToHumanAsync);
//        yield return AIFunctionFactory.Create(GetIvrWorkflowStateAsync);
//    }
//}

///// <summary>
///// Result of submitting input to the IVR workflow.
///// </summary>
//public class IvrInputResult
//{
//    public required bool Success { get; set; }
//    public required string Message { get; set; }
//    public required bool NeedsMoreInput { get; set; }
//    public string? NextPrompt { get; set; }
//}

///// <summary>
///// Result of changing the realtime agent persona.
///// </summary>
//public class PersonaChangeResult
//{
//    public required bool Success { get; set; }
//    public required string PersonaName { get; set; }
//    public required string Message { get; set; }
//}

///// <summary>
///// Result of handoff request to human operator.
///// </summary>
//public class HandoffResult
//{
//    public required bool Success { get; set; }
//    public required string HandoffId { get; set; }
//    public required string EstimatedWaitTime { get; set; }
//    public required string Message { get; set; }
//}

///// <summary>
///// Result containing the current IVR workflow state.
///// </summary>
//public class IvrStateResult
//{
//    public required string SessionId { get; set; }
//    public required string CurrentStep { get; set; }
//    public required string Status { get; set; }
//    public required List<string> CompletedSteps { get; set; }
//    public Dictionary<string, object>? CollectedData { get; set; }
//}
