{
 "title": "Azure OpenAI",
 "description": "Shows logs for requests and metrics from customMetrics collected from Azure API Management, Application Insights and Azure OpenAI.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Data source",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource group",
    "query": {}
   },
   {
    "name": "appinsight",
    "label": "App Insights",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "customMetrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customMetrics",
      "resources": [
       "/subscriptions/$sub/resourcegroups/$rg/providers/Microsoft.Insights/components/$appinsight"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "requests",
      "resources": [
       "/subscriptions/$sub/resourcegroups/$rg/providers/Microsoft.Insights/components/$appinsight"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "customMetrics - custom query",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customMetrics  \r\n| where name == 'Total Tokens' \r\n| extend parsedCustomDimensions = parse_json(customDimensions) \r\n| extend clientIP = tostring(parsedCustomDimensions.['Client IP']) \r\n| extend apiId = tostring(parsedCustomDimensions.['API ID']) \r\n| extend apimSubscription = tostring(parsedCustomDimensions.['Subscription ID']) \r\n| extend UserId = tostring(parsedCustomDimensions.['User ID']) \r\n| project timestamp, value, clientIP, apiId, apimSubscription, UserId \r\n| order by timestamp asc",
      "resources": [
       "/subscriptions/$sub/resourcegroups/$rg/providers/Microsoft.Insights/components/$appinsight"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "requests - custom query",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "requests  \r\n| project timestamp, duration, customDimensions \r\n| extend duration = round(duration, 2) \r\n| extend parsedCustomDimensions = parse_json(customDimensions) \r\n| extend apiName = tostring(parsedCustomDimensions.['API Name']) \r\n| extend apimSubscription = tostring(parsedCustomDimensions.['Subscription Name']) \r\n| extend userAgent = tostring(parsedCustomDimensions.['Request-User-agent']) \r\n| extend request_json = tostring(parsedCustomDimensions.['Request-Body']) \r\n| extend request = parse_json(request_json) \r\n| extend model = tostring(request.['model']) \r\n| extend messages = tostring(request.['messages']) \r\n| extend region = tostring(parsedCustomDimensions.['Response-x-ms-region']) \r\n| extend remainingTokens = tostring(parsedCustomDimensions.['Response-x-ratelimit-remaining-tokens']) \r\n| extend remainingRequests = tostring(parsedCustomDimensions.['Response-x-ratelimit-remaining-requests']) \r\n| extend response_json = tostring(parsedCustomDimensions.['Response-Body']) \r\n| extend response = parse_json(response_json) \r\n| extend promptTokens = tostring(response.['usage'].['prompt_tokens']) \r\n| extend completionTokens = tostring(response.['usage'].['completion_tokens']) \r\n| extend totalTokens = tostring(response.['usage'].['total_tokens']) \r\n| extend completion = tostring(response.['choices'][0].['message'].['content']) \r\n| project timestamp, apiName, apimSubscription, duration, userAgent, model, messages, completion, region, promptTokens, completionTokens, totalTokens, remainingTokens, remainingRequests \r\n| order by timestamp desc",
      "resources": [
       "/subscriptions/$sub/resourcegroups/$rg/providers/Microsoft.Insights/components/$appinsight"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "customMetrics",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "customMetrics",
      "resources": [
       "/subscriptions/$sub/resourcegroups/$rg/providers/Microsoft.Insights/components/$appinsight"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "requests",
      "resources": [
       "/subscriptions/$sub/resourcegroups/$rg/providers/Microsoft.Insights/components/$appinsight"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  }
 ]
}