
[build-system]
requires = [
    "setuptools>=80.9.0",
    "wheel",
    "grpcio-tools>=1.76.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "voice-biometrics-api"
version = "0.1.0"
description = "A Python gRPC microservice for voice biometric enrollment and verification using SpeechBrain's ECAPA-TDNN speaker recognition model."
requires-python = ">=3.12"
dependencies = [
    "grpcio>=1.76.0",
    "grpcio-tools==1.76.0",
    "grpcio-health-checking>=1.76.0",
    "opentelemetry-distro>=0.59b0",
    "opentelemetry-exporter-otlp>=1.28.2",
    "numpy>=2.3.5",
    "torch==2.9.1",
    "torchaudio==2.9.1",
    "speechbrain@git+https://github.com/speechbrain/speechbrain.git@develop",
    "hyperpyyaml>=1.2.2",
    "pytest>=7.4.0",
]

[project.optional-dependencies]
dev = [
    "pytest==7.4.0",
    "yamllint==1.35.1",
]


[tool.setuptools.packages.find]
where = ["."]
include = ["protos*", "models*"]
exclude = ["obj*", "build*", "tests", "tests.*"]

[tool.setuptools.cmdclass]
build_py = "build_protos.build_py"

[tool.setuptools]
py-modules = ["build_protos"]

[tool.uv.sources]
torch = [
{ index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
{ index = "pytorch-cu130", marker = "sys_platform == 'linux'" },
]
torchaudio = [
{ index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
{ index = "pytorch-cu130", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[project.scripts]
build-protos = "build_protos:build_main"
