<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageJsonName Condition="$(PackageJsonName) == ''">microsoft-agent-framework-starter</PackageJsonName>
    <PackageJsonVersion Condition="$(PackageJsonVersion) == ''">0.1.0</PackageJsonVersion>
    <PackageJsonPrivate Condition="$(PackageJsonPrivate) == ''">true</PackageJsonPrivate>
    <PackageJsonScriptsDevDebug Condition="$(PackageJsonScriptsDevDebug) == ''">LOG_LEVEL=debug npm run dev</PackageJsonScriptsDevDebug>
    <PackageJsonScriptsDev Condition="$(PackageJsonScriptsDev) == ''">next dev --turbopack</PackageJsonScriptsDev>
    <PackageJsonScriptsBuild Condition="$(PackageJsonScriptsBuild) == ''">next build</PackageJsonScriptsBuild>
    <PackageJsonScriptsStart Condition="$(PackageJsonScriptsStart) == ''">next start</PackageJsonScriptsStart>
    <PackageJsonScriptsLint Condition="$(PackageJsonScriptsLint) == ''">next lint</PackageJsonScriptsLint>
    <PackageJsonDependenciesAgUiClient Condition="$(PackageJsonDependenciesAgUiClient) == ''">0.0.41</PackageJsonDependenciesAgUiClient>
    <PackageJsonDependenciesAgUiLanggraph Condition="$(PackageJsonDependenciesAgUiLanggraph) == ''">^0.0.19</PackageJsonDependenciesAgUiLanggraph>
    <PackageJsonDependenciesAzureCommunicationCalling Condition="$(PackageJsonDependenciesAzureCommunicationCalling) == ''">^1.40.1</PackageJsonDependenciesAzureCommunicationCalling>
    <PackageJsonDependenciesAzureCommunicationCommon Condition="$(PackageJsonDependenciesAzureCommunicationCommon) == ''">3.0.0-beta.1</PackageJsonDependenciesAzureCommunicationCommon>
    <PackageJsonDependenciesAzureCommunicationIdentity Condition="$(PackageJsonDependenciesAzureCommunicationIdentity) == ''">1.4.0-beta.1</PackageJsonDependenciesAzureCommunicationIdentity>
    <PackageJsonDependenciesAzureMsalBrowser Condition="$(PackageJsonDependenciesAzureMsalBrowser) == ''">^4.26.2</PackageJsonDependenciesAzureMsalBrowser>
    <PackageJsonDependenciesAzureMsalReact Condition="$(PackageJsonDependenciesAzureMsalReact) == ''">^3.0.22</PackageJsonDependenciesAzureMsalReact>
    <PackageJsonDependenciesCopilotkitReactCore Condition="$(PackageJsonDependenciesCopilotkitReactCore) == ''">1.10.6</PackageJsonDependenciesCopilotkitReactCore>
    <PackageJsonDependenciesCopilotkitReactUi Condition="$(PackageJsonDependenciesCopilotkitReactUi) == ''">1.10.6</PackageJsonDependenciesCopilotkitReactUi>
    <PackageJsonDependenciesCopilotkitRuntime Condition="$(PackageJsonDependenciesCopilotkitRuntime) == ''">1.10.6</PackageJsonDependenciesCopilotkitRuntime>
    <PackageJsonDependenciesMicrosoftSignalr Condition="$(PackageJsonDependenciesMicrosoftSignalr) == ''">^10.0.0</PackageJsonDependenciesMicrosoftSignalr>
    <PackageJsonDependenciesNext Condition="$(PackageJsonDependenciesNext) == ''">15.3.2</PackageJsonDependenciesNext>
    <PackageJsonDependenciesReact Condition="$(PackageJsonDependenciesReact) == ''">^19.0.0</PackageJsonDependenciesReact>
    <PackageJsonDependenciesReactDom Condition="$(PackageJsonDependenciesReactDom) == ''">^19.0.0</PackageJsonDependenciesReactDom>
    <PackageJsonDependenciesZod Condition="$(PackageJsonDependenciesZod) == ''">^3.24.4</PackageJsonDependenciesZod>
    <PackageJsonDevdependenciesEslintEslintrc Condition="$(PackageJsonDevdependenciesEslintEslintrc) == ''">^3</PackageJsonDevdependenciesEslintEslintrc>
    <PackageJsonDevdependenciesTailwindcssPostcss Condition="$(PackageJsonDevdependenciesTailwindcssPostcss) == ''">^4</PackageJsonDevdependenciesTailwindcssPostcss>
    <PackageJsonDevdependenciesTypesNode Condition="$(PackageJsonDevdependenciesTypesNode) == ''">^20</PackageJsonDevdependenciesTypesNode>
    <PackageJsonDevdependenciesTypesReact Condition="$(PackageJsonDevdependenciesTypesReact) == ''">^19</PackageJsonDevdependenciesTypesReact>
    <PackageJsonDevdependenciesTypesReactDom Condition="$(PackageJsonDevdependenciesTypesReactDom) == ''">^19</PackageJsonDevdependenciesTypesReactDom>
    <PackageJsonDevdependenciesConcurrently Condition="$(PackageJsonDevdependenciesConcurrently) == ''">^9.1.2</PackageJsonDevdependenciesConcurrently>
    <PackageJsonDevdependenciesEslint Condition="$(PackageJsonDevdependenciesEslint) == ''">^9</PackageJsonDevdependenciesEslint>
    <PackageJsonDevdependenciesEslintConfigNext Condition="$(PackageJsonDevdependenciesEslintConfigNext) == ''">15.3.2</PackageJsonDevdependenciesEslintConfigNext>
    <PackageJsonDevdependenciesTailwindcss Condition="$(PackageJsonDevdependenciesTailwindcss) == ''">^4</PackageJsonDevdependenciesTailwindcss>
    <PackageJsonDevdependenciesTypescript Condition="$(PackageJsonDevdependenciesTypescript) == ''">^5</PackageJsonDevdependenciesTypescript>
  </PropertyGroup>
</Project>