# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biometrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'biometrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62iometrics.proto\x12\rbiometrics.v1\"A\n\rEnrollRequest\x12\x11\n\x07user_id\x18\x01 \x01(\tH\x00\x12\x15\n\x0b\x61udio_chunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"2\n\x0e\x45nrollResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"A\n\rVerifyRequest\x12\x11\n\x07user_id\x18\x01 \x01(\tH\x00\x12\x15\n\x0b\x61udio_chunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"<\n\x0eVerifyResponse\x12\x10\n\x08is_match\x18\x01 \x01(\x08\x12\x18\n\x10similarity_score\x18\x02 \x01(\x02\x32\xac\x01\n\x10\x42iometricService\x12K\n\nEnrollUser\x12\x1c.biometrics.v1.EnrollRequest\x1a\x1d.biometrics.v1.EnrollResponse(\x01\x12K\n\nVerifyUser\x12\x1c.biometrics.v1.VerifyRequest\x1a\x1d.biometrics.v1.VerifyResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biometrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENROLLREQUEST']._serialized_start=35
  _globals['_ENROLLREQUEST']._serialized_end=100
  _globals['_ENROLLRESPONSE']._serialized_start=102
  _globals['_ENROLLRESPONSE']._serialized_end=152
  _globals['_VERIFYREQUEST']._serialized_start=154
  _globals['_VERIFYREQUEST']._serialized_end=219
  _globals['_VERIFYRESPONSE']._serialized_start=221
  _globals['_VERIFYRESPONSE']._serialized_end=281
  _globals['_BIOMETRICSERVICE']._serialized_start=284
  _globals['_BIOMETRICSERVICE']._serialized_end=456
# @@protoc_insertion_point(module_scope)
