# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import biometrics_pb2 as biometrics__pb2
GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in biometrics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BiometricServiceStub(object):
    """Biometric service for speaker enrollment and verification
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnrollUser = channel.stream_unary(
                '/biometrics.v1.BiometricService/EnrollUser',
                request_serializer=biometrics__pb2.EnrollRequest.SerializeToString,
                response_deserializer=biometrics__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.VerifyUser = channel.stream_unary(
                '/biometrics.v1.BiometricService/VerifyUser',
                request_serializer=biometrics__pb2.VerifyRequest.SerializeToString,
                response_deserializer=biometrics__pb2.VerifyResponse.FromString,
                _registered_method=True)


class BiometricServiceServicer(object):
    """Biometric service for speaker enrollment and verification
    """

    def EnrollUser(self, request_iterator, context):
        """Enroll a user with their voice sample
        Client streams user_id (first message) followed by audio chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUser(self, request_iterator, context):
        """Verify a user against their enrolled voice sample
        Client streams user_id (first message) followed by audio chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BiometricServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnrollUser': grpc.stream_unary_rpc_method_handler(
                    servicer.EnrollUser,
                    request_deserializer=biometrics__pb2.EnrollRequest.FromString,
                    response_serializer=biometrics__pb2.EnrollResponse.SerializeToString,
            ),
            'VerifyUser': grpc.stream_unary_rpc_method_handler(
                    servicer.VerifyUser,
                    request_deserializer=biometrics__pb2.VerifyRequest.FromString,
                    response_serializer=biometrics__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biometrics.v1.BiometricService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('biometrics.v1.BiometricService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BiometricService(object):
    """Biometric service for speaker enrollment and verification
    """

    @staticmethod
    def EnrollUser(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/biometrics.v1.BiometricService/EnrollUser',
            biometrics__pb2.EnrollRequest.SerializeToString,
            biometrics__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyUser(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/biometrics.v1.BiometricService/VerifyUser',
            biometrics__pb2.VerifyRequest.SerializeToString,
            biometrics__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
