<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <!--<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>-->
    <OutputType>Exe</OutputType>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Testing" />

    <PackageReference Include="Microsoft.AspNetCore.Authentication" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\Showcase.Authentication\Showcase.Authentication.csproj" />
  </ItemGroup>

</Project>
